name: Daily Live Safety Evaluation

on:
  schedule:
    - cron: "0 4 * * *"   # 09:30 IST (after dataset job)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas matplotlib detoxify
      - name: Prepare small CI dataset (head 30 rows)
        run: |
          python - << 'PY'
          import pandas as pd, os
          src="data/live_prompts_latest.csv"
          out="data/live/_ci_latest.csv"
          os.makedirs("data/live", exist_ok=True)
          pd.read_csv(src).head(30).to_csv(out, index=False)
          print("Prepared", out)
          PY
      - name: Run tiny baseline (fast)
        run: |
          python -m benchmark.run_benchmark \
            --model_name sshleifer/tiny-gpt2 \
            --dataset_path data/live/_ci_latest.csv \
            --output_path results/sshleifer_tiny-gpt2_outputs.csv
      - name: Run distilgpt2 (light)
        run: |
          python -m benchmark.run_benchmark \
            --model_name distilgpt2 \
            --dataset_path data/live/_ci_latest.csv \
            --output_path results/distilgpt2_outputs.csv
      - name: Summarize + charts + toxicity
        run: |
          python .github/scripts/eval_and_publish.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-live-eval
          path: |
            results/*_outputs.csv
            results/*_summary.png
            results/summary_comparison.csv
            results/summary_all.json
      - name: Commit results to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "results: daily live safety evaluation (tiny + distilgpt2)"
          file_pattern: |
            results/*_summary.png
            results/summary_comparison.csv
            results/summary_all.json
