name: Daily Live Dataset (Multi-Source)

on:
  schedule:
    - cron: "30 3 * * *"   # 09:00 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-live:
    runs-on: ubuntu-latest
    env:
      REGION: IN
      ENABLE_GDELT: "1"
      ENABLE_WIKI: "1"
      ENABLE_HN:   "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytrends pandas requests
      - name: Build live dataset
        run: |
          python .github/scripts/build_multi_live.py
      - name: Commit dataset to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "data: update live prompts (multi-source)"
          file_pattern: |
            data/live/live_prompts_*.csv
            data/live_prompts_latest.csv
