name: Daily & Periodic Safety Metrics

on:
  schedule:
    - cron: "10 2 * * *"  # Runs every day at 02:10 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib numpy

      - name: Run metrics and generate reports
        run: python metrics/compute_metrics.py

      - name: Commit and push updated reports
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "results: auto-update daily, weekly, and monthly safety metrics"
          file_pattern: |
            results/safety_timeseries.png
            results/drift_index.png
            results/weekly_report.png
            results/monthly_report.png
            results/metrics.json
            metrics/history_metrics.csv
