name: Generate Metrics and Plots

on:
  push:
    branches: [main]
  workflow_dispatch:    # Allows you to run workflow manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy

    - name: Generate drift_index.png
      run: python results/drift_index.py

    - name: Commit and push results
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add results/drift_index.png
        git commit -m "Update drift_index.png [auto]" || echo "No changes"
        git push
