name: Daily Google Trends → Live Prompts CSV

on:
  schedule:
    # 09:00 IST == 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-dataset:
    runs-on: ubuntu-latest
    env:
      REGION: IN
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytrends pandas

      - name: Generate daily live prompts CSV
        run: |
          python .github/scripts/build_trends.py

      - name: Create Pull Request with dataset
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "data: add Google Trends live prompts dataset"
          title: "data: Google Trends live prompts dataset"
          body: |
            Adds a daily live prompts CSV from Google Trends.
            Region: ${{ env.REGION }}
          branch: "bot/trends-${{ github.run_id }}"
          labels: "data, automation"
